### ISSUE TITLE
Support `pyproject.toml` and `poetry` / `.python-version` file

### ISSUE THREAD

**Issue by sobolevn** [adamchainz/django-version-checks#20]
Hi!

There are two popular cases I use to specify python versions in my project:
- `pyproject.toml`: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/pyproject.toml#L19
- `.python-version`: https://github.com/wemake-services/wemake-django-template/blob/master/%7B%7Bcookiecutter.project_name%7D%7D/.python-version

It would be awesome to check that current runtime is in sync.

Any plans on supporting this? 🤔

**Comment by adamchainz** [comment]
I'm not sure it makes sense. This tool is for runtime checks, whilst such configuration files configure build/setup time tooling.  Also the checks here are to guard against the differences in multiple environments which often have different tools - and different versions whilst you're rolling out an upgrade. And I don't see a sensible way to combine the versions that might be declared in different tools - which should take precedence? What if they declare different versions?

If you really want to read from such files you can always do it with a line or two of reading + parsing e.g. 

```python
VERSION_CHECKS = {"python": "==" + Path(".python-version").read_text().strip()}
```
